#!/bin/bash
# copy from https://github.com/riobard/dotfiles/blob/master/setup

set -e

[ ! -e ~/code ] && mkdir -p ~/code

export DOTFILES_DIR=${HOME}/code/dotfiles

linkf() {
	[ -h ~/.$1 ] && rm -rf ~/.$1
	[ -e ~/.$1 ] && rm -rf ~/.$1
    ln -s $DOTFILES_DIR/home_root/$1  ~/.$1 
    echo ~/.$1 linked
    return 0
}

linkd() {
    [ -h ~/.config/$1 ] && rm -rf ~/.config/$1
    [ -e ~/.config/$1 ] && rm -rf ~/.config/$1
    ln -s $DOTFILES_DIR/config/$1  ~/.config/$1 
    echo ~/.config/$1 linked
    return 0
}

linkroot() {
    for file in $DOTFILES_DIR/home_root/*; do
        if [ -e $file ]; then
            linkf `basename $file` 
        fi
    done
    echo files in home_root linked
    return 0
}

linkconfig() {
	for conf in $DOTFILES_DIR/config/*;do
		if [ -e $conf ]; then
			linkd `basename $conf`
		fi
	done
	echo files in .config linked
	return 0
}

clone() {
    if ! [[ -d $DOTFILES_DIR ]]; then
        git clone https://github.com/dgeibi/dotfiles.git $DOTFILES_DIR
    else
        cd $DOTFILES_DIR
        git pull
    fi
    return 0
}

read -p "clone?[y/n]" yn
if [ "${yn}" == "Y" ] || [ "${yn}" == "y" ]; then
	clone
fi

linkroot
linkconfig
