#
# ~/.bash_profile
#

source ~/.profile

[[ -f ~/.bashrc ]] && source ~/.bashrc

systemctl --user import-environment PATH

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && command -v i3 &> /dev/null
then
    startx
fi
