#
# ~/.bash_profile
#

source ~/.profile

[[ -f ~/.bashrc ]] && . ~/.bashrc

systemctl --user import-environment PATH

if [[ -z $DISPLAY ]] && command -v i3 && [[ $(tty) = /dev/tty1 ]]; then
    startx
fi

