#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# lock and turn off monitor when idle

if type xautolock > /dev/null && type i3lock > /dev/null; then
    DPMS_StandbyTime=600
    DPMS_SuspendTime=600
    DPMS_OffTime=600
    X11ScreenSaver_Timeout=600
    xautolock -time 10 -locker "i3lock -c 000000" &
    xset dpms $DPMS_StandbyTime $DPMS_SuspendTime $DPMS_OffTime
    xset s $X11ScreenSaver_Timeout
fi

# set primary monitor

xrandr --output "$(xrandr | grep -m 1 "\bconnected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")" --primary

# set background

bgdir="$HOME"/Pictures/bg/
if type feh > /dev/null && [ -d "$bgdir" ]; then
    feh --recursive --randomize --bg-fill "$bgdir"
fi

# set language

#export LANG=zh_CN.UTF-8
#export LANGUAGE=zh_CN:en_US
#export LC_CTYPE=en_US.UTF-8

# set fcitx as default input method

if type fcitx > /dev/null; then
    export GTK_IM_MODULE=fcitx
    export QT_IM_MODULE=fcitx
    export XMODIFIERS="@im=fcitx"
fi

# configurate QT

export GTK2_RC_FILES="$HOME"/.gtkrc-2.0
export QT_SELECT=5
export QT_STYLE_OVERRIDE=GTK+

# execute i3wm

if type i3 > /dev/null; then
    exec i3
fi
