#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# configurate QT

export GTK2_RC_FILES="$HOME"/.gtkrc-2.0
export QT_SELECT=5
export QT_STYLE_OVERRIDE=gtk2
export QT_QPA_PLATFORMTHEME=gtk2

# set language

#export LANG=zh_CN.UTF-8
#export LANGUAGE=zh_CN:en_US
#export LC_CTYPE=en_US.UTF-8

useibus() {
    if type ibus > /dev/null; then
        export GTK_IM_MODULE=ibus
        export XMODIFIERS=@im=ibus
        export QT_IM_MODULE=ibus
    fi
}

usefcitx() {
    if type fcitx > /dev/null; then
        export GTK_IM_MODULE=fcitx
        export QT_IM_MODULE=fcitx
        export XMODIFIERS="@im=fcitx"
    fi
}

usefcitx

extra() {
    dbus-update-activation-environment --systemd :0
    eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
    export SSH_AUTH_SOCK

    SET_DPMS=false

    # set background
    bgdir="$HOME"/Pictures/bg/
    if type feh > /dev/null && [ -d "$bgdir" ]; then
        feh --recursive --randomize --bg-fill "$bgdir"
    fi

    # launch copyq
    if type copyq > /dev/null; then
        copyq &
    fi

    # launch dropbox
    if type dropbox > /dev/null; then
        dropbox &
    fi

    # launch goldendict
    if type goldendict > /dev/null; then
        goldendict &
    fi

    # run compton
    if type compton > /dev/null; then
        compton -b
    fi

    if $SET_DPMS; then
        DPMS_StandbyTime=600
        DPMS_SuspendTime=600
        DPMS_OffTime=600
        X11ScreenSaver_Timeout=600

        xset dpms $DPMS_StandbyTime $DPMS_SuspendTime $DPMS_OffTime
        xset s $X11ScreenSaver_Timeout
    fi

    # lock and turn off monitor when idle
    #if type xautolock > /dev/null && type i3lock > /dev/null; then
       # xautolock &
    #fi

    # set primary monitor
    xrandr --output "$(xrandr | grep -m 1 "\bconnected" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")" --primary
    # set dpi
    xrandr --dpi 130
    togglepad off
}

session=${1:-i3}
case $session in
    i3|i3wm           ) extra; exec i3;;
    mate              ) exec mate-session;;
    xp1                ) exec VirtualBox -startvm "xp-1";;
    xp2                ) exec VirtualBox -startvm "xp-2";;
    xp0                ) exec VirtualBox -startvm "xp-0";;
    win1032           ) exec VirtualBox -startvm "Windows 10";;
    win10             ) exec VirtualBox -startvm "win10-0";;
    *) exec "$1";;
esac
