#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

DPMS_StandbyTime=600
DPMS_SuspendTime=600
DPMS_OffTime=600
X11ScreenSaver_Timeout=600

xautolock -time 10 -locker "i3lock -c 000000" &
xset dpms $DPMS_StandbyTime $DPMS_SuspendTime $DPMS_OffTime
xset s $X11ScreenSaver_Timeout

[[ -n "$(/usr/bin/xrandr | grep 'eDP-1' )" ]] && xrandr --output eDP-1 --primary

feh --recursive --randomize --bg-fill /usr/share/backgrounds/
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US
export LC_CTYPE=en_US.UTF-8
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export QT_SELECT=5
export QT_STYLE_OVERRIDE=GTK+
exec i3
